---
title: Pankaj Parashar - Designer. Developer. Writer.
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: email@pankajparashar.com
description: Hello. I'm Pankaj Parashar, 30yo Designer, Developer and Writer from
  Mumbai India.  I write code to make a living and write about them on my blog here.
baseurl: "/"
url: https://pankajparashar.com
twitter_username: pankajparashar
github_username: pankajparashar
highlighter: rouge
permalink: "/posts/:title/"
