title: "Pankaj Parashar: Designer. Developer. Writer."
email: email@pankajparashar.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello. I'm Pankaj Parashar, 30yo Designer, Developer and Writer from Mumbai India. 
  I write code to make a living and write about them on my blog here.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://pankajparashar.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pankajparashar
github_username:  pankajparashar

# Build settings
permalink: "/posts/:title/"
theme: minima
future: true
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 15
paginate_path: page/:num