title: Pankaj Parashar
email: email@pankajparashar.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm a Designer, Developer and Writer from Mumbai India. I write
  code to make a living and write about them on my blog here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pankajparashar
github_username:  pankajparashar

# Build settings
permalink: "/posts/:title/"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5
paginate_path: page/:num